name: "Dispatched Workflow"
on:
  workflow_dispatch:
    inputs:
      parameter1:
        type: string
        required: true
        description: "Parameter 1"
#jobs:
#  dispatched-job:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#        echo "Parameter 1: ${{ github.event.inputs.parameter1 }}"
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run my script
        run: |
          echo "Parameter 1: ${{ github.event.inputs.parameter1 }}"
