name: "Dispatched Workflow"
on:
  workflow_dispatch:
    inputs:
      parameter1: # workflow_dispatchイベントで受け取るパラメータを定義
        type: string
        required: true
        description: "Parameter 1"
jobs:
  dispatched-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Parameter 1: ${{ github.event.inputs.parameter1 }}"
