name: "Dispatched Workflow"
on:
  workflow_dispatch:
    inputs:
      parameter1:
        type: string
        required: true
        description: "Parameter 1"
jobs:
  dispatched-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "parameter1: ${{ github.event.inputs.parameter1 }}"
