name: "Scheduled workflow"
on:
  workflow_dispatch: # workflow_dispatchイベントを使って動作確認するため
  schedule:
    - cron: '*/5 * * * *' # 5分ごとに実行

jobs:
  main-job:
    name: "Scheduled job"
    runs-on: ubuntu-latest
    permissions:
      actions: write # 'gh workflow run'コマンド実行のため

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # リモートブランチをすべて取得するため

      - name: "Run workflow with workflow_dispatch event"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          parameter_list=$(mktemp)
          git branch -r | # リモートブランチの一覧を出力
          sed 's;[^/]*/;;' | # --refオプションに与えるのに不要な部分を削除
          tee "${parameter_list}" | # あとから表示させるためにファイルに保存
          xargs -I @ gh workflow run dispatched_workflow.yaml --ref "@" -f parameter1="@"

          # パラメーターのリストを出力
          echo "### Parameter list BEGIN ###"
          cat "${parameter_list}"
          echo "### Parameter list END ###"
